---
all:
  children:
    vps:
      hosts:
        racknerd-vps:
          ansible_host: 192.210.150.73
          ansible_user: root
    k3s_servers:
      hosts:
        salad-playground:
          ansible_host: 192.168.0.69
          ansible_user: salad
          ansible_become: true